version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Porta 3000 no host mapeada para porta 80 no container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

